# Netlify configuration for TRINE AI Music Label website

[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# SPA rewrite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Global security headers (single block)
[[headers]]
  for = "/*"
  [headers.values]
    # Clickjacking: use CSP frame-ancestors + XFO as legacy fallback
    X-Frame-Options = "DENY"
    Content-Security-Policy = '''
      default-src 'self';
      frame-src 'self' https://bandcamp.com https://*.bandcamp.com;
      frame-ancestors 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob: https://*.bandcamp.com;
      media-src 'self' https: blob:;
      connect-src 'self' https: wss:;
      worker-src 'self' blob:;
      upgrade-insecure-requests;
    '''
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # (Optional legacy header — mostly ignored by modern browsers)
    X-XSS-Protection = "1; mode=block"

# Long-term cache for hashed static assets (put your built files under /assets/)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# If you also serve images from another folder, add another block, e.g.:
# [[headers]]
#   for = "/images/*"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000, immutable"

# (Avoid patterns like "*.png" — they won’t match nested paths.)
